In [1]:
import os
os.getcwd()


'c:\\Users\\Acer\\Desktop\\nlp_course_folder'

In [2]:
robert_frost='robert_frost.txt'
edgar_allan_poe='edgar_allan_poe.txt'


In [3]:
type(robert_frost)

str

In [4]:
lines=[]
with open(robert_frost, "r", encoding="utf-8") as f:
    for line in f:
        line=line.strip()
        if line:
            lines.append(line)

In [5]:
lines

['Two roads diverged in a yellow wood,',
 'And sorry I could not travel both',
 'And be one traveler, long I stood',
 'And looked down one as far as I could',
 'To where it bent in the undergrowth;',
 'Then took the other, as just as fair,',
 'And having perhaps the better claim',
 'Because it was grassy and wanted wear,',
 'Though as for that the passing there',
 'Had worn them really about the same,',
 'And both that morning equally lay',
 'In leaves no step had trodden black.',
 'Oh, I kept the first for another day!',
 'Yet knowing how way leads on to way',
 'I doubted if I should ever come back.',
 'I shall be telling this with a sigh',
 'Somewhere ages and ages hence:',
 'Two roads diverged in a wood, and I,',
 'I took the one less traveled by,',
 'And that has made all the difference.',
 'Whose woods these are I think I know.',
 'His house is in the village, though;',
 'He will not see me stopping here',
 'To watch his woods fill up with snow.',
 'My little horse must think it q

In [6]:
def file_to_list(txt_file):
    lines=[]
    with open(txt_file,'r',encoding="utf-8") as f:
        for line in f:
            line=line.strip()
            if line:
                lines.append(line)
    return lines

In [7]:
texts=[]
labels=[]

# 0 represents robert frost , 1 represents edgar allan poe

frost= file_to_list(robert_frost)


for i in frost:
    texts.append(i)
    labels.append(0)

poe=file_to_list(edgar_allan_poe)

for i in poe:
    texts.append(i)
    labels.append(1)

In [8]:
print(len(texts))
print(len(labels))
print(texts[:3])
print(labels[:3])
print(texts[-3:])
print(labels[-3:])

2154
2154
['Two roads diverged in a yellow wood,', 'And sorry I could not travel both', 'And be one traveler, long I stood']
[0, 0, 0]
['Through the pale door,', 'A hideous throng rush out forever,', 'And laugh --but smile no more.']
[1, 1, 1]


In [9]:
from sklearn.model_selection import train_test_split


In [10]:
x_train, x_test, y_train, y_test=train_test_split(texts,labels,test_size=0.2,random_state=42)

In [11]:
print(len(x_train), len(x_test))
print(len(y_train), len(y_test))
print(x_train[:3])
print(y_train[:3])



1723 431
1723 431
["'The voices seem to say- - '", "Of all who, on Despair's unhallowed bed", 'Of the tower clock']
[0, 1, 0]


In [16]:
from nltk.tokenize import word_tokenize


In [17]:
import nltk
nltk.download('punkt', quiet=True)

True

In [14]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt to C:\Users\Acer/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Acer/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [18]:
# Creating the vocabulary
current_idx=1
word2idx={'<unk>':0}
for doc in x_train:
    tokens=word_tokenize(doc)
    for j in tokens:
        if j not in word2idx:
            word2idx[j]=current_idx
            current_idx+=1



In [19]:
import numpy as np



In [ ]:
# #  instead of having x_train which is a list of strings, ew will have x_train_S which is a list of lists

# x_train_S=[]
# S1=[]
# for doc in x_train:
#     tokens=word_tokenize(doc)
#     for token in tokens:
#         idx=word2idx[token]
#         S1.append(idx)
#         x_train_S.append(S1)

# x_test_S=[]
# S2=[]
# for doc in x_test:
#     tokens=word_tokenize(doc)
#     for token in tokens:
#         if token in word2idx:
#             idx=word2idx[token]
#             S2.append(idx)
#         else:
#             S2.append(0)

#         x_test_S.append(S2)

In [21]:
x_train_S = []

for doc in x_train:
    S = []
    tokens = word_tokenize(doc)
    for token in tokens:
        idx = word2idx.get(token, 0)
        S.append(idx)
    x_train_S.append(S)

x_test_S = []

for doc in x_test:
    S = []
    tokens = word_tokenize(doc)
    for token in tokens:
        idx = word2idx.get(token, 0)
        S.append(idx)
    x_test_S.append(S)

In [22]:
x_test_S

[[98, 0, 65, 152, 1146, 33, 0, 135],
 [168, 270, 28, 1661, 252, 1662, 159],
 [90, 28, 486, 77, 1999, 17, 1549, 0, 6, 7],
 [1202, 17, 0, 11, 0, 35, 63, 0, 11],
 [512, 17, 52, 11, 59, 9, 17, 443, 1422, 11],
 [50, 0, 329, 50, 1498, 642, 0, 1165],
 [666, 1764, 837, 35, 182, 1100, 1994, 39],
 [0, 50, 532, 423, 0, 0, 11],
 [1027, 218, 17, 782, 68, 0, 39],
 [84, 0, 35, 9, 17, 397, 163, 25],
 [493, 50, 1104, 4, 0, 4, 299],
 [84, 1029, 1030, 50, 81, 900, 4],
 [50, 772, 342, 716, 25, 73, 11, 50, 157, 128, 342, 66, 25],
 [776, 265, 839, 0, 11, 0, 11, 0],
 [103, 2459, 352, 163, 116, 334, 335, 25],
 [452, 33, 1367, 11],
 [378, 0, 1048, 0, 11, 47, 63, 2450, 11],
 [307, 554, 17, 813, 240, 114, 17, 0, 11],
 [192, 17, 240, 35, 63, 1221, 244, 226],
 [61, 352, 114, 0, 35, 0, 310, 89, 25],
 [0, 2072],
 [168, 59, 50, 343, 0, 47, 1367, 25],
 [2092, 47, 11, 7, 1262, 1263, 2192, 89, 0, 25],
 [119, 2271, 233, 2272, 59, 234, 226],
 [269, 2615, 21, 51, 1910, 17, 2606, 936, 35, 170, 16, 11],
 [45, 17, 0, 35, 836,

In [ ]:
# # converting x_train which is a list of strings to x_train_vec which is a list of lists
# x_train_vec=[]
# for i in x_train:
#     V = np.zeros(len(word2idx))

#     tokens=word_tokenize(i)
#     for token in tokens:
#         if token in word2idx:
#             idx=word2idx[token]
#             V[idx]+=1
#     x_train_vec.append(V)

In [ ]:
# # converting x_test which is a list of strings to x_test_vec which is a list of lists
# x_test_vec=[]
# for i in x_test:
#     V = np.zeros(len(word2idx))

#     tokens=word_tokenize(i)
#     for token in tokens:
#         if token in word2idx:
#             idx=word2idx[token]
#             V[idx]+=1
#     x_test_vec.append(V)

In [24]:
x_train_frost = [x_train_S[i] for i in range(len(y_train)) if y_train[i] == 0]
x_train_poe   = [x_train_S[i] for i in range(len(y_train)) if y_train[i] == 1]

In [25]:
#  computing pi for frost
N=len(x_train_frost)
V=len(word2idx)
pi_frost=np.zeros(V)

for i in x_train_frost:
    if len(i)>0:
        h=i[0]
        pi_frost[h]+=1
pi_frost/=N

#  computing pi for poe

M=len(x_train_poe) 
pi_poe=np.zeros(V)

for i in x_train_poe:
    if len(i)> 0:
        L=i[0]
        pi_poe[L]+=1
pi_poe/=M



In [26]:
pi_poe[800:810]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
pi_frost

array([0.        , 0.00344828, 0.        , ..., 0.00086207, 0.        ,
       0.        ], shape=(2968,))

In [28]:
# computing A
#  computing add_one smoothed A for frost
A_frost_smoothed=np.zeros((V,V))
H_frost_smoothed=np.zeros(V)
for seq in x_train_frost:
    for i in range(len(seq)-1):
        A_frost_smoothed[seq[i], seq[i+1]] += 1
        H_frost_smoothed[seq[i]]+=1



In [29]:
A_frost_smoothed.shape           # (V, V)
# A_frost.sum(axis=1)     # rows ≈ 1 where H[i] > 0


(2968, 2968)

In [30]:
######## add_one smoothing for pi
#  computing add_one smoothined pi for frost


N_frost=len(x_train_frost)
V=len(word2idx)
pi_frost_smoothed=np.zeros(V)

for i in x_train_frost:
    if len(i)>0:
        h=i[0]
        pi_frost_smoothed[h]+=1
pi_frost_smoothed+=1
pi_frost_smoothed/=(N_frost+V)

#  computing add_one smoothed pi for poe

N_poe=len(x_train_poe) 
pi_poe_smoothed=np.zeros(V)

for i in x_train_poe:
    if len(i)> 0:
        L=i[0]
        pi_poe_smoothed[L]+=1
pi_poe_smoothed+=1
pi_poe_smoothed/=(N_poe+V)




In [31]:
#  sanity check
pi_frost_smoothed.sum()   # ≈ 1.0
pi_poe_smoothed.sum()     # ≈ 1.0


np.float64(1.0)

In [32]:
A_frost_smoothed+=1
H_frost_smoothed+=V

for i in range(V):
    if H_frost_smoothed[i] > 0:
        A_frost_smoothed[i] /= H_frost_smoothed[i]

# computing add_one smoothed A for poe

A_poe_smoothed=np.zeros((V,V))
H_poe_smoothed=np.zeros(V)
for seq in x_train_poe:
    for i in range(len(seq)-1):
        A_poe_smoothed[seq[i], seq[i+1]] += 1
        H_poe_smoothed[seq[i]]+=1

A_poe_smoothed+=1
H_poe_smoothed+=V

for i in range(V):
    if H_poe_smoothed[i] > 0:
        A_poe_smoothed[i] /= H_poe_smoothed[i]

In [33]:
A_frost_smoothed.sum(axis=1)[:10]
A_poe_smoothed.sum(axis=1)[:10]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
# p(author=frost)
probability_author_frost= len(x_train_frost)/(len(x_train_frost)+len(x_train_poe))

# p(author=poe)
probability_author_poe= len(x_train_poe)/(len(x_train_frost)+len(x_train_poe))
poem=input("enter the poem:")

def string_to_seq(poem):
    poem_seq=[]
    tokens = word_tokenize(poem)
    for token in tokens:
        idx = word2idx.get(token, 0)
        poem_seq.append(idx)
    return poem_seq

poem_seq=string_to_seq(poem)

# p(poem|frost)
probability_frost=np.log(pi_frost_smoothed[poem_seq[0]])
for i in range(len(poem_seq)-1):

    probability_frost+=np.log(A_frost_smoothed[poem_seq[i],poem_seq[i+1]])


# p(poem|poe)
probability_poe=np.log(pi_poe_smoothed[poem_seq[0]])
for i in range(len(poem_seq)-1):

    probability_poe+=np.log(A_poe_smoothed[poem_seq[i],poem_seq[i+1]])


probability_frost += np.log(probability_author_frost)
probability_poe   += np.log(probability_author_poe)


# Final decision (argmax)
if probability_frost > probability_poe:
    print("Author: Frost")
else:
    print("Author: Poe")


Author: Frost
